import express from "express";
import cors from "cors";
import scheduleRoutes from "./routes/scheduleRoutes.js";
const app = express();
app.use(cors()); 
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static("public"));
app.use("/class-schedules", scheduleRoutes);
export { app };
